<?php
$helperData = $this->helper('Excellence\Hello\Helper\Data');
$helperData->getBannerConfig();
?>
<div id="bannervideo">
    <div class="video-background">
        <div class="video-foreground">
            <iframe height="800vw" width="100%" src="<?= $helperData->getBannerConfig() ?>?rel=0&modestbranding=1&autohide=1&mute=1&showinfo=0&controls=0&autoplay=1" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
    <div class="content1">
        <h1><?= $block->escapeHtmlAttr(__('Shopping')) ?></h1>
        <p><?= $block->escapeHtmlAttr(__('Lorem ipsum dolor sit amet, an his etiam torquatos. Tollit soleat phaedrum te duo, eum cu recteque expetendis neglegentur. Cu mentitum maiestatis persequeris pro, pri ponderum tractatos ei. Id qui nemore latine molestiae, ad mutat oblique delicatissimi pro')) ?>.</p>
        <button id="myBtn" onclick="myFunction()"><?= $block->escapeHtmlAttr(__('SHOP')) ?></button>
    </div>
</div>
</div>
