<div class="container1">
<!-- <h2>STAY CONNECTED dvfdvv dcdvdvdv dvvvsvsvsv sdvsvs</h2> -->
<div id="text">
    <center>
        <span class="staymsg">
<?= $block->escapeHtmlAttr(__('STAY CONNECTED'))?>
</span>
<input id="stay_connected" type="text" placeholder="<?= $block->escapeHtmlAttr(__('ENTER YOUR EMAIL'))?>"/>
<button class="shop"><?= $block->escapeHtmlAttr(__('WOMEN'))?></button>
<button class="shop2"><?= $block->escapeHtmlAttr(__('MEN'))?></button>
<center>
</div>
</div>

